[project]
name = "pydantic-mcp-example"
version = "0.1.8"
description = "PydanticAI MCP example"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai-slim[mcp,openai]>=2.20.0",
]

[dependency-groups]
dev = [
    "mqtt-mcp>=0.3.3",
    "pre-commit>=4.6.1",
    "ruff>=0.16.0",
]
